namespace Domain.Enums;

public enum DocumentType
{
    UPLOADED_TRANSCRIPT_JSON = 1,
    DECISION_LETTER_DEANS_OFFICE = 2,
    INFORMATION_LETTER_TO_DEPT = 3,
    DIPLOMA_MAIN = 4,
    DIPLOMA_CERTIFICATE_HONOUR = 5,
    DIPLOMA_CERTIFICATE_HIGH_HONOUR = 6,
    STUDENT_LIST_EXPORTED = 7,
    ADVISOR_GRADUATION_REPORT = 8,
    DISENGAGEMENT_FORM = 9,
    OTHER = 10
    // Kaldırılan Değerler: COVER_LETTER_TEMPLATE_DEPT, COVER_LETTER_UPLOADED_DEPT
} 