namespace Domain.Enums;

public enum GraduationProcessStatus
{
    AWAITING_DEPT_SECRETARY_TRANSCRIPT_UPLOAD = 1,
    TRANSCRIPT_UPLOADED_PENDING_PARSE = 2,
    TRANSCRIPT_PARSE_SUCCESSFUL_PENDING_ADVISOR_CHECK = 3,
    TRANSCRIPT_PARSE_ERROR_AWAITING_REUPLOAD = 4,
    ADVISOR_ELIGIBLE = 5,
    ADVISOR_NOT_ELIGIBLE = 6,
    PENDING_DEPT_SECRETARY_APPROVAL = 7,
    DEPT_SECRETARY_APPROVED_PENDING_DEAN = 8,
    DEPT_SECRETARY_REJECTED_PROCESS = 9,
    PENDING_DEANS_OFFICE_REVIEW = 10,
    DEANS_OFFICE_APPROVED = 11,
    DEANS_OFFICE_REJECTED = 12,
    PENDING_STUDENT_AFFAIRS_FINALIZATION = 13,
    STUDENT_AFFAIRS_APPROVED = 14,
    STUDENT_AFFAIRS_REJECTED = 15,
    ELIGIBLE_FOR_GRADUATION_DOCS = 16,
    GRADUATION_DOCS_PREPARED = 17,
    COMPLETED_GRADUATED = 18,
    PROCESS_TERMINATED_BY_ADMIN = 19
} 