namespace Domain.Enums;

public enum StudentGraduationStatus
{
    ACTIVE_STUDENT = 1,
    GRADUATION_PROCESS_INITIATED_AWAITING_TRANSCRIPT = 2,
    TRANSCRIPT_PROCESSING_BY_SYSTEM = 3,
    PENDING_ELIGIBILITY_REVIEW_BY_ADVISOR = 4,
    IN_APPROVAL_PROCESS = 5,
    GRADUATED = 6,
    GRADUATION_DENIED_FINAL = 7,
    DISMISSED = 8,
    PASSIVE = 9
} 